---
# yaml-language-server: $schema=https://raw.githubusercontent.com/google/yamlfmt/main/schema.json
formatter:
  type: basic
  indent: 2
  include_document_start: true
  line_ending: lf
  retain_line_breaks: true
  retain_line_breaks_single: true
  disallow_anchors: false
  max_line_length: 120
  scan_folded_as_literal: true
  indentless_arrays: false
  drop_merge_tag: false
  pad_line_comments: 1
  trim_trailing_whitespace: true
  eof_newline: true
  disable_alias_key_correction: true
