---
extends: default

ignore: |-
  core/src/main/resources/locales/

rules:
  braces:
    max-spaces-inside: 1
  comments:
    # prettier compatibility
    min-spaces-from-content: 1
  comments-indentation: false
  line-length:
    max: 160
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  truthy: disable
