---
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: kotlin-faker
# ref: https://www.mkdocs.org/user-guide/configuration/#site_url
# ref: https://www.mkdocs.org/user-guide/configuration/#environment-variables
site_url: !ENV [MKDOCS_SITE_URL, 'http://localhost:8000']
copyright: Copyright &copy; 2019 - present, serpro69

repo_url: https://github.com/serpro69/kotlin-faker

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - panzoom:
      always_show_hint: true
  - include_dir_to_nav

theme:
  favicon: assets/images/favicon.ico
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: nord:light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: nord:dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
  logo: assets/images/icon.png
  custom_dir: material

extra:
  version:
    provider: mike

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - abbr
  - footnotes
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.snippets:
      base_path:
        # https://www.mkdocs.org/user-guide/configuration/#paths-relative-to-the-current-file-or-site
        - !relative $config_dir
        - !relative $docs_dir
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: serpro69
      repo: kotlin-faker

nav:
  - "~/": index.md
  - API: api
