package com.github.sergio.igwt.kfaker

import io.kotlintest.*
import io.kotlintest.matchers.haveKeys
import io.kotlintest.matchers.numerics.*
import io.kotlintest.specs.*

internal class FakerServiceTest : FreeSpec() {

    init {
        "GIVEN dictionary is loaded" - {

            "WHEN locale is set to default value" - {
                val dictionary = FakerService().dictionary

                "THEN it should contain all keys for 'en' locale" {
                    run {
                        dictionary should haveKeys(
                            "address",
                            "ancient",
                            "creature",
                            "app",
                            "appliance",
                            "aqua_teen_hunger_force",
                            "artist",
                            "back_to_the_future",
                            "bank",
                            "basketball",
                            "beer",
                            "bojack_horseman",
                            "book",
                            "bossa_nova",
                            "breaking_bad",
                            "buffy",
                            "business",
                            "cannabis",
                            "chuck_norris",
                            "code",
                            "coffee",
                            "coin",
                            "color",
                            "commerce",
                            "community",
                            "company",
                            "compass",
                            "construction",
                            "cosmere",
                            "crypto_coin",
                            "culture_series",
                            "currency",
                            "dc_comics",
                            "demographic",
                            "dessert",
                            "device",
                            "games",
                            "dragon_ball",
                            "dr_who",
                            "dumb_and_dumber",
                            "dune",
                            "educator",
                            "electrical_components",
                            "esport",
                            "family_guy",
                            "file",
                            "finance",
                            "food",
                            "football",
                            "the_fresh_prince_of_bel_air",
                            "friends",
                            "funny_name",
                            "game_of_thrones",
                            "gender",
                            "ghostbusters",
                            "grateful_dead",
                            "greek_philosophers",
                            "hacker",
                            "harry_potter",
                            "heroes",
                            "heroes_of_the_storm",
                            "hey_arnold",
                            "hipster",
                            "hitchhikers_guide_to_the_galaxy",
                            "hobbit",
                            "house",
                            "how_i_met_your_mother",
                            "id_number",
                            "industry_segments",
                            "internet",
                            "invoice",
                            "job",
                            "kpop",
                            "lebowski",
                            "lord_of_the_rings",
                            "lorem",
                            "lovecraft",
                            "markdown",
                            "marketing",
                            "measurement",
                            "michael_scott",
                            "military",
                            "movie",
                            "music",
                            "name",
                            "nation",
                            "nato_phonetic_alphabet",
                            "new_girl",
                            "one_piece",
                            "parks_and_rec",
                            "phish",
                            "phone_number",
                            "cell_phone",
                            "country_code",
                            "princess_bride",
                            "programming_language",
                            "quote",
                            "relationship",
                            "restaurant",
                            "rick_and_morty",
                            "rock_band",
                            "rupaul",
                            "science",
                            "seinfeld",
                            "shakespeare",
                            "silicon_valley",
                            "simpsons",
                            "slack_emoji",
                            "source",
                            "south_park",
                            "space",
                            "stargate",
                            "star_trek",
                            "star_wars",
                            "stranger_things",
                            "stripe",
                            "subscription",
                            "superhero",
                            "sword_art_online",
                            "team",
                            "the_expanse",
                            "the_it_crowd",
                            "the_thick_of_it",
                            "twin_peaks",
                            "umphreys_mcgee",
                            "university",
                            "vehicle",
                            "venture_bros",
                            "verbs",
                            "v_for_vendetta",
                            "world_cup",
                            "yoda"
                        )
                    }
                }

                "THEN recurring keys should be appended" {
                    dictionary["creature"]?.keys?.size!! shouldBeGreaterThan 1
                    dictionary["games"]?.keys?.size!! shouldBeGreaterThan 1
                }
            }
        }
    }
}
