site:
  theme: Copper
  baseUrl: http://localhost:8080
  about:
    siteName: kotlin-faker
    siteDescription: |-
      kotlin-faker is a data-generation library intended for use during development and testing.
      It can also be sucessfully used for data-anonymization purposes.
      It generates realistically looking fake data such as names, addresses, banking, internet details, and many more.
    social:
      other:
        - link: '/kotlin-faker'
          label: 'Home'
          icon: 'fas fa-home'
          buttonColor: 'dark'
        - label: 'GitHub'
          icon: 'fab fa-github'
          link: 'https://github.com/serpro69/kotlin-faker/'
          buttonColor: 'dark'

theme:
  primaryColor: '#7E80CF'
  bannerColor: '#444444'
  linkColor: '#7E80CF'
  infoColor: '#A97BFF'

  colors:
    purple: '#7E83C4'
    green: '#7EB394'
    black: '#444444'
  palette:
    primary: 'PURPLE'
    link: 'PURPLE'
    secondary: 'GREEN'
    linkVisited: 'GREEN'

  extraCss:
    - asset: 'assets/css/bulma.min.css'
      download: false
    - asset: 'assets/css/extras.scss'
      download: false
    - asset: 'assets/css/homepage.scss'
      download: false
    - asset: 'assets/css/plugins.scss'
      download: false
  extraJs:
    - asset: 'assets/js/simpleFilter.js'
      download: false
    - asset: 'https://code.iconify.design/2/2.0.1/iconify.min.js'
      download: true

  menu:
    - type: 'page'
      title: 'Home'
      itemId: 'home'
      icon: 'home'
    - type: 'wiki'
      icon: 'graduation-cap'
      asSubmenu: true
      submenuTitle: 'User Guide'
    - type: 'submenu'
      title: 'API'
      icon: 'book'
      menu:
        - type: 'sourcedocModules'
          moduleType: 'kotlindoc'
          moduleGroup: 'core-api'
        - type: 'sourcedocModules'
          moduleType: 'kotlindoc'
          moduleGroup: 'core-provider'
        - type: separator
        - type: 'sourcedocModules'
          moduleType: 'kotlindoc'
          moduleGroup: 'faker-module'
        - type: separator
        - type: 'sourcedocModules'
          moduleType: 'kotlindoc'
          moduleGroup: 'faker-extension'
    - type: 'submenu'
      title: 'Information'
      icon: 'info-circle'
      menu:
        - type: 'page'
          title: 'About'
          itemId: 'About'
        - type: 'page'
          itemId: 'Changelog'
        - type: 'page'
          title: 'Contributing'
          itemId: 'Contributing'
        - type: 'page'
          title: 'Faker Comparisons'
          itemId: 'Faker Comparisons'
        - type: 'page'
          title: 'License'
          itemId: 'License'
        - type: 'page'
          title: 'Thanks'
          itemId: 'Ack'
  metaComponents:
    - type: 'orchidSearch'
      extraCss:
        - 'assets/css/orchidSearch.scss'
    - type: 'prism'
      theme: 'tomorrow'
#      scriptsOnly: 'true'
      extraCss:
        - 'assets/css/prism-duotone.css'
      languages:
        - clike
        - markup-templating
        - kotlin
        - java
        - groovy
        - yaml
        - yml
        - asciidoc
        - markdown
        - twig
        - xml

services:
  publications:
    stages:
      - type: githubPages
        branch: gh-pages
        username: serpro69
        repo: kotlin-faker

kotlindoc:
  # Uncomment `homePageOnly` line to temporarily disable Kotlin docs generation and only
  #   generate module homepages. Dokka takes a few seconds to start up, which
  #   makes rapid iteration a bit painful, so it may be helpful to disable it
  #   when making changes to the site.
  homePageOnly: true
  homePagePermalink: 'modules/:module'
  sourcePagePermalink: ':moduleType/:module/:sourceDocPath'
  sourcePages:
    menu:
      - type: 'sourcedocPageLinks'
        itemTitleType: 'signature' # optional, one of [NAME, ID, SIGNATURE]
        includeItems: true # optional
  modules:
    # :core
    - { name: 'Full Core API',                 slug: 'core-api',                  sourceDirs: [ './../../../../core/src/main/kotlin/', './../../../../core/src/main/java/' ],                 moduleGroup: 'core-api'        }
    - { name: 'Core Data Provider API',        slug: 'core-data-provider',        sourceDirs: [ './../../../../core/src/main/kotlin/io/github/serpro69/kfaker/provider' ],                    moduleGroup: 'core-provider'   }
    # :faker
    - { name: 'Books Provider API',            slug: 'books-data-provider',       sourceDirs: [ './../../../../faker/books/src/main/kotlin/io/github/serpro69/kfaker/books' ],                moduleGroup: 'faker-module'    }
    - { name: 'Commerce Provider API',         slug: 'commerce-data-provider',    sourceDirs: [ './../../../../faker/commerce/src/main/kotlin/io/github/serpro69/kfaker/commerce' ],          moduleGroup: 'faker-module'    }
    - { name: 'Creatures Provider API',        slug: 'creatures-data-provider',   sourceDirs: [ './../../../../faker/creatures/src/main/kotlin/io/github/serpro69/kfaker/creatures' ],        moduleGroup: 'faker-module'    }
    - { name: 'Databases Provider API',        slug: 'databases-data-provider',   sourceDirs: [ './../../../../faker/databases/src/main/kotlin/io/github/serpro69/kfaker/databases' ],        moduleGroup: 'faker-module'    }
    - { name: 'Edu Provider API',              slug: 'edu-data-provider',         sourceDirs: [ './../../../../faker/edu/src/main/kotlin/io/github/serpro69/kfaker/edu' ],                    moduleGroup: 'faker-module'    }
    - { name: 'Games Provider API',            slug: 'games-data-provider',       sourceDirs: [ './../../../../faker/games/src/main/kotlin/io/github/serpro69/kfaker/games' ],                moduleGroup: 'faker-module'    }
    - { name: 'Humor Provider API',            slug: 'humor-data-provider',       sourceDirs: [ './../../../../faker/humor/src/main/kotlin/io/github/serpro69/kfaker/humor' ],                moduleGroup: 'faker-module'    }
    - { name: 'JapMedia Provider API',         slug: 'japmedia-data-provider',    sourceDirs: [ './../../../../faker/japmedia/src/main/kotlin/io/github/serpro69/kfaker/japmedia' ],          moduleGroup: 'faker-module'    }
    - { name: 'Lorem Provider API',            slug: 'lorem-data-provider',       sourceDirs: [ './../../../../faker/lorem/src/main/kotlin/io/github/serpro69/kfaker/lorem' ],                moduleGroup: 'faker-module'    }
    - { name: 'Misc Provider API',             slug: 'misc-data-provider',        sourceDirs: [ './../../../../faker/misc/src/main/kotlin/io/github/serpro69/kfaker/misc' ],                  moduleGroup: 'faker-module'    }
    - { name: 'Movies Provider API',           slug: 'movies-data-provider',      sourceDirs: [ './../../../../faker/movies/src/main/kotlin/io/github/serpro69/kfaker/movies' ],              moduleGroup: 'faker-module'    }
    - { name: 'Music Provider API',            slug: 'music-data-provider',       sourceDirs: [ './../../../../faker/music/src/main/kotlin/io/github/serpro69/kfaker/music' ],                moduleGroup: 'faker-module'    }
    - { name: 'Sports Provider API',           slug: 'sports-data-provider',      sourceDirs: [ './../../../../faker/sports/src/main/kotlin/io/github/serpro69/kfaker/sports' ],              moduleGroup: 'faker-module'    }
    - { name: 'Tech Provider API',             slug: 'tech-data-provider',        sourceDirs: [ './../../../../faker/tech/src/main/kotlin/io/github/serpro69/kfaker/tech' ],                  moduleGroup: 'faker-module'    }
    - { name: 'Travel Provider API',           slug: 'travel-data-provider',      sourceDirs: [ './../../../../faker/travel/src/main/kotlin/io/github/serpro69/kfaker/travel' ],              moduleGroup: 'faker-module'    }
    - { name: 'TvShows Provider API',          slug: 'tvshows-data-provider',     sourceDirs: [ './../../../../faker/tvshows/src/main/kotlin/io/github/serpro69/kfaker/tvshows' ],            moduleGroup: 'faker-module'    }
    # :extension
    - { name: 'Blns Extension API',            slug: 'blns-extension',            sourceDirs: [ './../../../../extension/blns/src/main/kotlin/io/github/serpro69/kfaker/blns' ],              moduleGroup: 'faker-extension' }
    - { name: 'Kotest Property Extension API', slug: 'kotest-property-extension', sourceDirs: [ './../../../../extension/kotest-property/src/main/kotlin/io/github/serpro69/kfaker/kotest' ], moduleGroup: 'faker-extension' }

snippets:
  sections:
    - tags: [ 'code_snippets' ]
      adapter:
        type: 'embedded'
        baseDirs:
          - '../../../../core/src/main/resources/locales/en/'
          - '../../../../core/src/integration/kotlin/'
          - '../../../../faker/books/src/integration/kotlin/'
          - '../../../../faker/commerce/src/integration/kotlin/'
          - '../../../../faker/movies/src/integration/kotlin/'
          - '../../../../faker/tvshows/src/integration/kotlin/'
          - '../../../../core/src/integration/java/'
          - 'snippets'
        recursive: true
        startPattern: '^.*?[//|#].*?START(.+?)$'
        endPattern: '^.*?[//|#].*?END(.+?)$'
        patternNameGroup: 1

changelog:
  adapter:
    type: "file"
    baseDir: "../../../../"
    filename: CHANGELOG.adoc
#    versionRegex: '^\#\#\s\[\d+\.\d+\.\d+\]'
